import { useState } from 'react';
import Head from 'next/head';

import ReactMapGL from 'react-map-gl';
import 'mapbox-gl/dist/mapbox-gl.css'

import { FaInstagram, FaFacebookF, FaTwitter } from 'react-icons/fa'

import Menu from '../../components/Menu';
import Rodape from '../../components/Rodape';
import Link from '../../components/Link';

import styles from './Contact.module.scss';

export default function Contact() {
  const [viewport, setViewport] = useState({
    width: "100%",
    height: 400,
    latitude: -10.9058422,
    longitude: -37.0516275,
    zoom: 15,
  });

  return (
    <>
      <Head>
        <title>Pizzaria Inácio - Entre em contato e adiquira a sua pizza</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Menu />
      <main>
        <section className={"section " + styles.contact}>
          <div className="container">
            <h2 className="title">Make your Order</h2>
            <h3 className={styles.description}>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus incidunt et harum alias corporis fugiat!</h3>
            <div className={styles.contactContent} >
              <form onSubmit={(event)=> event.preventDefault()} className={styles.formContact}>
                <div className="wrap-name">
                  <input type="text" id="name" placeholder="Name" required />
                </div>

                <div className="wrap-email">
                  <input type="email" id="email" placeholder="E-mai" required />
                </div>

                <div className="wrap-adress">
                  <input type="text" id="adress" placeholder="Address" required />
                </div>

                <div className={styles.wrapHowManyAndTelphone}>
                  <div className={styles.wrapHowMany}>
                    <input type="number" min="1" max="10" placeholder="How many?" />
                  </div>

                  <div className={styles.wrapTelephone}>
                    <input type="tel" id="telephone" placeholder="Telephone number" required />
                  </div>
                </div>

                <div className={styles.wrapOrder}>
                  <textarea id="order" placeholder="Mais de um sabor? Informe o sabores separados por virgula" required></textarea>
                </div>
                <div className={styles.wrapSubmit}>
                  <button type="submit" className="btn">Enviar</button>
                </div>
              </form>

              <div className={styles.contactData}>
                <div className={styles.address}>
                  <h3 className={styles.subtitle}>Date contact</h3>
                  <ul className="contact-adress">
                    <li>- +55 7 8954-5423</li>
                    <li>- pedidos@telepizza.com</li>
                    <li>- Rua Gracho Cardoso - Brasília</li>
                    <li>- Avenida Brasil - Rio de janeiro</li>
                  </ul>
                </div>

                <div className={styles.socialNetwork}>
                  <h2 className={styles.subtitle}>Redes Sociais</h2>
                  <div className={styles.wrapSocialNetwork}>
                    <Link to="https://www.facebook.com/">
                      <FaFacebookF />
                    </Link>

                    <Link to="https://www.instagram.com/">
                      <FaInstagram />
                    </Link>

                    <Link to="https://twitter.com/">
                      <FaTwitter />
                    </Link>
                  </div>
                </div>
              </div>
            </div>

            <div className={styles.map}>
              <ReactMapGL {...viewport} onViewportChange={nextViewport => setViewport(nextViewport)} mapboxApiAccessToken={'pk.eyJ1IjoiamZsYXZpbzIyMCIsImEiOiJja3JsMmRrbmo0cW0yMnFyMnhuNGgzMTJjIn0.3SDzYhxk47a-KRzqmEO4qQ'} mapStyle="mapbox://styles/mapbox/outdoors-v11" />
            </div>
          </div>
        </section>
      </main>

      <Rodape />
    </>
  );
}