import React from 'react';
import Head from 'next/head'
import { FaChevronRight } from 'react-icons/fa';

import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, {  Pagination } from 'swiper/core';
import 'swiper/swiper.min.css'
import 'swiper/components/pagination/pagination.min.css';
import 'swiper/components/scrollbar/scrollbar.min.css'

import Menu from '../components/Menu';
import Link from '../components/Link';
import Card from '../components/Card';
import HeaderNotification from '../components/HeaderNotification';

import styles from '../styles/Home.module.scss';
import Testimony from '../components/Testimony';

SwiperCore.use([Pagination]);

export default function Home() {

  const data = {
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    title: 'Calabresa',
    priceOld: '25,60',
    priceNew: '25,80',
    description: 'Mussarela, calabresa, queijo',
  }

  const data2 = {
    imageurl: 'https://images.unsplash.com/photo-1615439244365-b9b37c99f29c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=341&q=80',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam voluptate molestias voluptatem natus architecto earum laboriosam quaerat quibusdam voluptas autem, eos fugit sapiente quia aut excepturi, exercitationem possimus, aperiam commodi.',
    author: 'Cristina Barbosa',
    cityState: 'Japaratuba/SE',
  }


  return (
    <>

      <Head>
        <title>Pizzaria Inácio - Faça já o seu pedido</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <HeaderNotification />
      <Menu />

      <main id={styles.main} className="gap">

        <section className={styles.introduction}>
          <div className="container">
            <div className={styles.bannerIntroduction}>
              <h3 className={styles.titleBanner}>Super oferta!!!</h3>
              <p className={styles.bannerIntroductionText}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
              </p>

              <div className={styles.bannerIntroductionFooter}>
                <Link to="/" className="btn">About more</Link>
                <Link to="/" className="btn btn-outline">Add cart</Link>
              </div>
            </div>
          </div>
        </section>

        <section className={'section ' + styles.portfolio}>
          <div className="container">
            <h2 className="title">Telecombo semanal!!!</h2>
            <div className={styles.cards}>
              <Card data={data} />
              <Card data={data} />
            </div>

            <footer>
              <div className={styles.callAction}>
                <p>Não ficou satisfeito com tele combo? temos outras opções!!!</p>
                <a href="" className="btn btn-yellow cta">
                  Ver cardápio completo
                  <FaChevronRight />
                </a>
              </div>
            </footer>
          </div>
        </section>

        <section className={'section ' + styles.testimonials}>
          <div className="container">
            <h2 className="title">Testimonials</h2>
            <div className={"section"}>
              <Swiper
                spaceBetween={50}
                slidesPerView={1}
                centeredSlides= {true}
                pagination={{
                  clickable:true,
                }}
                loop={false}
                speed={1000}
                autoplay={{
                  delay: 1000,
                  disableOnInteraction: false,
                  waitForTransition: true,
                }}
              >
                <SwiperSlide>
                  <span><Testimony data={data2} /></span>
                </SwiperSlide>

                <SwiperSlide>
                  <span><Testimony data={data2} /></span>
                </SwiperSlide>

              </Swiper>
            </div>
          </div>
        </section>

        <section className={'section ' + styles.banner}>
            <div className="container">
                <h3 className="banner">Tele premium <br /> oferta!!!<br /></h3>
                <div className="value">
                    <span className="real">
                        R$
                    </span>
                    <span className="price">
                        59,90
                    </span>
                </div>

            </div>

        </section>

      </main>
    </>
  )
}
