import Head from 'next/head'
import React from 'react';

import Menu from '../components/Menu';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pizzaria Inácio - Faça já o seu pedido</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Menu />

      <main id={styles.main}>
        <section className={'section ' + styles.introduction}>
          <div className="container">
            <div className="card">
              <h3 className="card-title">Super oferta!!!</h3>
              <div className="card-body">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                </p>
              </div>

              <div className="card-footer">
                <a href="" className="btn">About more</a>
                <a href="" className="btn btn-outline">Add cart</a>
              </div>
            </div>
          </div>

        </section>
      </main>


    </>
  )
}
