import Head from 'next/head';

import Card from '../../components/Card';
import PageIntroduction from '../../components/PageIntroduction';
import styles from './Cardapio.module.scss';

import { useCardapio } from '../../contexts/MenuTestimonialsContext';

export default function Cardapio() {

  const { menu } = useCardapio();

  return (
    <>

    <Head>
      <title>Telepizza - Nosso cardápio completo</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
      <main className={styles.cardapio}>

        <PageIntroduction style={{background: 'radial-gradient( #d92027, #DD1D86)'}}>

          <div className={styles.headerWrapper}>
            <h2 className="title">Nosso cardapio completo</h2>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facere cupiditate quo recusandae aliquam.</p>
          </div>
          <footer>
            <p>Showing <span>{menu.length}</span> results</p>
          </footer>
        </PageIntroduction>


        <section className={"section " + styles.listCardapio}>
          <div className="container">
            <div className={styles.cards}>
              {menu.map((item, index) => {
                return (
                  index < 6 && (
                    <Card data={item} key={item.id} />
                  )
                )
              })}
            </div>
          </div>
        </section>
      </main>
    </>
  );
}